apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: enhancements
  annotations:
    github.com/project-slug: lokanandaprabhu/enhancements
spec:
  type: other
  lifecycle: unknown
  owner: user:development/guest
